---

- hosts: all
  remote_user: pi
  gather_facts: yes
  become: yes

  roles:
    - { role: ssh, tags: ['ssh'] }
    - { role: sslh, tags: ['sslh'] }
    - { role: owncloud, tags: ['owncloud'] }
    - { role: s3ql, tags: ['s3ql'] }
    - { role: attic, tags: ['attic'] }
    - { role: duckdns, tags: ['duckdns'] }

  # todo: https
