---

- hosts: all
  remote_user: pi
  gather_facts: yes
  become: yes

  roles:
    - { role: system, tags: ['system'] }
    - { role: ssh, tags: ['ssh'] }
    - { role: sslh, tags: ['sslh'] }
    - { role: owncloud, tags: ['owncloud'] }
    - { role: https, tags: ['https'] }
    - { role: s3ql, tags: ['s3ql'] }
    - { role: attic, tags: ['attic'] }
    - { role: duckdns, tags: ['duckdns'] }

#todo: s3ql not starting at boot
#todo: monitoring
#  - last attic backup (date/status)
#  - attic backup consistency
#  - s3ql consistency
