---

- hosts: all
  remote_user: pi
  gather_facts: no
  become: yes

  roles:
    - { role: system, tags: ['system'] }
    - { role: tlsdate, tags: ['tlsdate'] }
    - { role: ssh, tags: ['ssh'] }
    - { role: sslh, tags: ['sslh'] }
    - { role: owncloud, tags: ['owncloud'] }
    - { role: https, tags: ['https'] }
    - { role: s3cmd, tags: ['s3cmd'] }
    - { role: attic, tags: ['attic'] }
    - { role: duckdns, tags: ['duckdns'] }
    - { role: gogs, tags: ['gogs'] }

#TODO: configure gogs attic backup
#todo: monitoring
#  - last attic backup (date/status)
