---

- hosts: all
  remote_user: pi
  gather_facts: no
  become: yes

  roles:
    - { role: system, tags: ['system'] }
    - { role: tlsdate, tags: ['tlsdate'] }
    - { role: ssh, tags: ['ssh'] }
    - { role: sslh, tags: ['sslh'] }
    - { role: owncloud, tags: ['owncloud'] }
    - { role: https, tags: ['https'] }
    - { role: s3cmd, tags: ['s3cmd'] }
    - { role: attic, tags: ['attic'] }
    - { role: duckdns, tags: ['duckdns'] }
    - { role: gogs, tags: ['gogs'] }
    - { role: monitoring, tags: ['monitoring'] }

#todo: monitoring
#  - last attic backup (date/status)
#  - don't backup if machine is not provisioned
#  - restart sslh (and other service binding to single interface) on wicd postconnect
#  - on first provisioning, certificates do not exist and https will refuse to start. Temporarily disable ssl.conf file?
#  - 'https' role is getting a little overloaded. Evaulate splitting letsencrypt and keybase into separate roles
