---

#TODO: define here the Proxy settings for apache

- name: enable apache modules
  apache2_module: name=proxy_http state=present
  notify: restart httpd

#TODO: reload systemd conf
- name: template systemd file
  template: src=gogs.service.j2 dest=/etc/systemd/system/multi-user.target.wants/gogs.service
  notify:
    - reload systemd
    - restart gogs
