---

- name: install git
  apt: name="git" state=latest

- name: create git group
  group: name=git state=present

- name: create git user
  user: name=git group=git state=present createhome=yes

#TODO: define here the Proxy settings for apache

- name: template gogs.conf
  template: src=gogs.conf.j2 dest=/etc/apache2/conf-enabled/gogs.conf
  notify: restart httpd

- name: enable apache modules
  apache2_module: name=proxy_http state=present
  notify: restart httpd

- name: template systemd file
  template: src=gogs.service.j2 dest=/etc/systemd/system/multi-user.target.wants/gogs.service
  notify:
    - reload systemd
    - restart gogs
