---

- apt: name=s3ql state=present

- name: template s3ql_thebluebox_authfile
  template: src=s3ql_authfile.j2 dest={{ s3ql_thebluebox_authfile }} mode=0600

- name: template /etc/init.d/s3ql
  template: src=s3ql-init.j2 dest=/etc/init.d/s3ql mode=0755

- name: cron s3ql (workaround)
  cron: name="Ensure s3ql is mounted" minute="0" job="/etc/init.d/s3ql start >/dev/null 2>/dev/null" state=present

#- name: enable s3ql dummy service
#  service: name=s3ql enabled=yes

- name: check s3ql-thebluebox-backup mount
  shell: mount | grep '{{ s3ql_thebluebox_storage_url }} on {{ s3ql_thebluebox_mountpoint }} type fuse.s3ql'
  register: s3ql_thebluebox_backup_mounted
  failed_when: False
  changed_when: 's3ql_thebluebox_backup_mounted.rc != 0'

- name: create {{ s3ql_thebluebox_mountpoint }}
  file: path={{ s3ql_thebluebox_mountpoint }} mode=0000 state=directory
  when: 's3ql_thebluebox_backup_mounted.rc != 0'

- name: mount s3ql-thebluebox-backup
  command: 'mount.s3ql --authfile {{ s3ql_thebluebox_authfile }} {{ s3ql_thebluebox_storage_url }} {{ s3ql_thebluebox_mountpoint }}'
  when: 's3ql_thebluebox_backup_mounted.rc != 0'
