---

- name: set hostname
  hostname: name=thebluebox.duckdns.org

- name: increase usb power
  lineinfile: dest=/boot/config.txt regexp=^max_usb_current line="max_usb_current=1" state=present

- name: check if rootfs is expanded
  stat: path=/.rootfs_expanded
  register: rootfs_expanded
  changed_when: rootfs_expanded.stat['exists'] == False
  notify:
    - expand rootfs
    - mark rootfs as expanded

- name: configure network interfaces
  copy: src=interfaces dest=/etc/network/interfaces backup=yes

- name: configure wifi
  template: src=wpa_supplicant.conf.j2 dest=/etc/wpa_supplicant/wpa_supplicant.conf backup=yes
