---

- name: Copy certificate file
  copy: content="{{ ssl_crt }}" dest=/etc/apache2/cert.pem owner=www-data
  notify: restart httpd

- name: Copy certificate key
  copy: content="{{ ssl_key }}" dest=/etc/apache2/privkey.pem owner=www-data
  notify: restart httpd

- name: Copy certificate chain
  copy: content="{{ ssl_chain }}" dest=/etc/apache2/chain.pem owner=www-data
  notify: restart httpd

- name: template ssl.conf
  template: src=ssl.conf.j2 dest=/etc/apache2/sites-enabled/ssl.conf
  notify: restart httpd

- name: enable apache modules
  apache2_module: name={{ item }} state=present
  with_items: ['ssl','headers']
  notify: restart httpd
