---

- apt: name={{ item }} state=present
  with_items: [libacl1-dev, python3-pip]

- pip: name=Attic executable=pip-3.2 state=latest

- template: src=attic-cron.j2 dest=/usr/local/sbin/attic-cron mode=0700

- cron: name="Owncloud backup with Attic" minute="0" hour="*" job="/usr/local/sbin/attic-cron" state=present
