---

- apt: name={{ item }} state=present
  with_items: [libacl1-dev, python3-pip]

- pip: name=Attic executable=pip-3.2 state=latest

# attic -> - template: src=s3ql-init.j2 dest=/etc/init.d/s3ql mode=0755
