---

- name: owncloud repository key
  apt_key: url='http://download.opensuse.org/repositories/isv:ownCloud:community/Debian_7.0/Release.key' state=present

- name: owncloud repository
  apt_repository: repo='deb http://download.opensuse.org/repositories/isv:/ownCloud:/community/Debian_7.0/ /' state=present

- name: owncloud package
  apt: name="{{ item }}" state=latest
  with_items: [owncloud, php-apc]
  notify: restart https

- name: enable apc commandline for owncloud maintenance mode
  lineinfile: dest=/etc/php5/mods-available/apc.ini regexp=^apc.enable_cli line='apc.enable_cli=1' backup=yes state=present
