---

- name: owncloud repository key
  apt_key: url='http://download.opensuse.org/repositories/isv:ownCloud:community/Debian_7.0/Release.key' state=present

- name: owncloud repository
  apt_repository: repo='deb http://download.opensuse.org/repositories/isv:/ownCloud:/community/Debian_7.0/ /' state=present

- name: owncloud package
  apt: name="{{ item }}" state=latest
  with_items: [owncloud, php-apc]
  notify: restart httpd

- name: enable apc commandline for owncloud maintenance mode
  lineinfile: dest=/etc/php5/mods-available/apc.ini regexp=^apc.enable_cli line='apc.enable_cli=1' backup=yes state=present

- name: install sqlite3 for backup db
  apt: name=sqlite3 state=present

- name: enable well-known url
  copy: src=htaccess dest=/var/www/.htaccess owner=root group=www-data backup=yes

- name: install libapache2-mod-php5 (workaround)
  apt: name=libapache2-mod-php5 state=present
  notify: restart httpd

- name: uninstall libapache2-mod-php5filter (workaround)
  apt: name=libapache2-mod-php5filter state=absent
  notify: restart httpd
